### ISSUE TITLE
WISH: parallel::detectCores() -> parallelly::availableCores()

### ISSUE THREAD

**Issue by HenrikBengtsson** [quantixed/TrackMateR#10]
`readTrackMateXML()` parallelizes on all hardware CPU cores by default:

https://github.com/quantixed/TrackMateR/blob/d6b981f00c4024d61ffae183b47aaf5a78fb8d2d/R/readTrackMateXML.r#L54

Using `parallel::detectCores()` is problematic for many reasons.  I explain why in my ['Please Avoid detectCores() in your R Packages'](https://www.jottr.org/2022/12/05/avoid-detectcores/) 2022-12-05 blog post.  The simplest fix is to address most of the problems is to replace it with `parallelly::availableCores()`.

FWIW, [`availableCores()`](https://parallelly.futureverse.org/reference/availableCores.html) is also agile to `_R_CHECK_LIMIT_CORES_`, so you can replace all of:

https://github.com/quantixed/TrackMateR/blob/d6b981f00c4024d61ffae183b47aaf5a78fb8d2d/R/readTrackMateXML.r#L48-L55

with 

```r
numCores <- parallelly::availableCores()
```

**Comment by quantixed** [comment]
You convinced me. Now added.
